CREATE TABLE OO (N INT NULL, P INT NULL)
GO

INSERT INTO OO
SELECT 1 , 2 
UNION ALL 
SELECT 3 , 2 
UNION ALL 
SELECT 6 , 8
UNION ALL  
SELECT 9 , 8
UNION ALL  
SELECT 2 , 5
UNION ALL  
SELECT 8 , 5
UNION ALL  
SELECT 5 , NULL
GO

SELECT N
	, CASE WHEN P IS NULL THEN 'Root'
		WHEN EXISTS (SELECT 1 FROM OO WHERE P=B.N) THEN 'Inner'
		ELSE 'Leaf'
		END
FROM OO AS B ORDER BY N;
